### ISSUE TITLE
Command fail in interactive mode WGS

### ISSUE THREAD

**Issue by laugon10** [roland-rad-lab/MoCaSeq#6]
Hi,
 Working in interactive mode on WGS with the commands provided in the nature paper, I have seen that there is a missing value in the command for CNVs.

-paper:

```
i) Run HMMCopy, using 20-kB windows, as follows:
sh $repository_dir/CNV_RunHMMCopy.sh $name Mouse $config_file 20000 Tumor Normal
```

I have tried this and the pipeline continues generating a file with the name "$name.Tumor.Normal.wig". It continues working without error for more than a day.
 So I think that a **MS** is missing

```
i) Run HMMCopy, using 20-kB windows, as follows:
sh $repository_dir/CNV_RunHMMCopy.sh $name Mouse $config_file MS 20000 Tumor Normal
```
Thank you!

**Comment by NikdAK** [comment]
Hi, 
thank you for the information, indeed the runmode ("MS") is missing in the documentation. This is probably due to an updated version of CNV_RunHMMCopy.sh.

The current full command can be found at line 905 of the MoCaSeq main script: 
`sh $repository_dir/CNV_RunHMMCopy.sh $name $species $config_file $runmode $resolution $types`

The problem is, that without a given $runmode, the other arguments will be shifted by 1 and HMMCopy will try to work on a resolution of "Tumor" instead of "20000". It is interesting that the tool will continue without errors.

Anyways, while looking into CNV_RunHMMCopy.sh I noticed that $runmode is a redundant parameter, It will just set $types, which are already given by the last argument. 
Therefore we will remove the $runmode parameter in the next release to make it consistent with the commands in the publication. This change will now already be available in the developmental branch (human-pipeline).

Additionally: I recommend defining the last argument with quotes to prevent parsing issues (`"Tumor Normal"`) .
